---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: qlik/gradle
    tag: latest

inputs:
- name: test-s3-resource
- name: apigateway-version

outputs:
- name: builds

run:
  path: test-s3-resource/build.sh
